### ISSUE TITLE
12Bit DAC LUT code for use with high antenna gain not included in Win32 build

### ISSUE THREAD

**Issue by Dunax** [Mictronics/pluto-gps-sim-win32#2]
Hi,

The 32bit win version does not have the "12-bit IQ DAC amplitude" experimental option, I assume this was not ported for this reason? 

I would be interested to test the 12bit Dac version in windows. (Improvement by using 9-bit sin/cos tables generating the baseband signal?)

I notice you have changed the gain setting (iq_gain) for the satellites to 100 for this and only 18 for the 16bit IQ dac section of your baseband generation code.

Your comments in the unix/c build state this was for:
/*
 * Uncomment to use only 12Bit DAC LUT with high antenna gain.
 * 
 * By default use 16Bit DAC LUT with low antenna gain.
 * Full DAC dynamic range -> Better SNR and signal quality, faster 3D lock.
 */

As a matter of interest, the default ADALM PLuto antenna - [Jinchang Electron - JCG401]https://wiki.analog.com/_media/university/tools/pluto/users/jcg401.pdf)
and review here: https://ez.analog.com/thread/100485-adalm-pluto-antenna-performance

Is this the antenna you used when testing the IQ for 12 vs 16 ? Did the 12bit work better on the generic Jinchang antenna? 

I have seen a suggestion to use this antenna: https://www.adafruit.com/product/1858 - any suggestions?

Missing in your Readme from the original gps-sdr-sim repository is the mention of the correct coupling method to devices. Might be handy to include this for other Pluto enthusiasts?

**Transmitting the samples**
The TX port of a particular SDR platform is connected to the GPS receiver under test through a DC block and a fixed 50-60dB attenuator.

**Comment by Mictronics** [comment]
The 12bit LUT was only for testing the IQ conversion and resulting RF spectrum. For 16bit a lower gain is required since generated IQ data for all satellites are summed up and then feed the DAC. Gain will be multiplied to each satellite IQ pair. So, when you gain is to high the IQ values will reach the 16bit max and the DAC will go in saturation, in turn the RF output signal gets distorted significantly.

The antenna itself has not much influence on signal generation. Of course for GPS you should have a RH circular polarized. My tests where performed mostly with a spectrum analyzer and when needed, with Pluto's OEM antenna (Jinchang). 

Added your README request for compliance.

**Comment by Dunax** [comment]
Thanks for your detailed response. Great work on your Pluto version. It is much appreciated!
